# roles/k8s_cpn
---
- name: Install util packages
  package:
    name:
      - bash-completion
      - bridge-utils
      - net-tools
      - cloud-utils
      - curl
    update_cache: yes
    state: latest
  become: true

- name: Configure kubectl completion and alias
  blockinfile:
    path: ~/.bashrc
    block: |
      source <(kubectl completion bash)
      alias k=kubectl
      complete -F __start_kubectl k

- name: Check flux install
  command: which flux
  register: flux

- name: Install flux
  shell: curl -s https://fluxcd.io/install.sh | bash
  when: flux.stdout | length == 0

- name: Check if CPN needs initializing
  stat:
    path: /etc/kubernetes/admin.conf
  register: kubeadm_init
  become: true

- name: Preflight checks
  command: kubeadm init phase preflight
  when: not kubeadm_init.stat.exists
  register: kubeadm_checks
  become: true

- name: Print preflight checks
  debug:
    var:
      kubeadm_checks.stdout
  when: not kubeadm_init.stat.exists

- name: Initialize CPN
  command: kubeadm init
  when: not kubeadm_init.stat.exists
  become: true

- name: Create .kube directory
  file:
    path: ~/.kube/
    state: directory
    force: false

- name: Copy k8s config
  copy:
    remote_src: true
    src: /etc/kubernetes/admin.conf
    dest: /home/ansible/.kube/config
  become: true

- name: Download Calico manifest
  get_url:
    url: https://raw.githubusercontent.com/projectcalico/calico/master/manifests/calico.yaml
    dest: /home/ansible/calico.yaml

- name: Install Calico
  k8s:
    state: present
    src: /home/ansible/calico.yaml

- name: Generate new token with join command
  tags: k8s_join_cluster
  command: kubeadm token create --print-join-command
  register: k8s_join_cmd

- name: Print join command
  tags: k8s_join_cluster
  debug:
    var: k8s_join_cmd.stdout

- name: Set join command
  tags: k8s_join_cluster
  set_fact:
    k8s_join_cmd: "{{ k8s_join_cmd.stdout_lines[0] }}"