---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
spec:
  chart:
    spec:
      chart: postgresql-ha
      version: 12.3.2
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: sources
      interval: 12h0m0s
  interval: 1h0m0s
  valuesFrom:
    - kind: ConfigMap
      name: values