---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: postgresql
spec:
  provider: vault
  secretObjects:
    - data:
        - key: password
          objectName: password
        - key: admin-password
          objectName: admin-password
        - key: repmgr-password
          objectName: repmgr-password
      secretName: postgresql
      type: Opaque
  parameters:
    vaultAddress: http://vault.secrets-store.svc.cluster.local:8200
    roleName: default
    objects: |
      - objectName: password
        secretPath: secret/data/postgresql
        secretKey: master-pass
      - objectName: repmgr-password
        secretPath: secret/data/postgresql
        secretKey: master-pass
      - objectName: admin-password
        secretPath: secret/data/postgresql
        secretKey: master-pass