---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: postgresql
spec:
  provider: vault
  secretObjects:
    - data:
        - key: master-pass
          objectName: master-pass
      secretName: postgresql
      type: Opaque
  parameters:
    vaultAddress: http://vault.secrets-store.svc.cluster.local:8200
    roleName: default
    objects: |
      - objectName: master-pass
        secretPath: secret/postgresql
        secretKey: master-pass