---
apiVersion: v1
kind: ConfigMap
metadata:
  name: values
data:
  values.yaml: |
    postgresql:
      replicaCount: 3
      priorityClassName: system-node-critical
      pdb:
        create: true
        minAvailable: 2

      maxConnections: 40
      postgresConnectionLimit: 2
      dbUserConnectionLimit: 10

      extraVolumes:
        - name: secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: postgresql
      extraVolumeMounts:
        - name: secrets
          mountPath: /etc/secrets
          readOnly: true
      existingSecret: postgresql

      resources:
        requests:
          cpu: 5m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 128Mi

    pgpool:
      priorityClassName: system-node-critical
      pdb:
        create: true
        minAvailable: 1

      extraVolumes:
        - name: secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: postgresql
      extraVolumeMounts:
        - name: secrets
          mountPath: /etc/secrets
          readOnly: true
      existingSecret: postgresql

      resources:
        requests:
          cpu: 5m
          memory: 128Mi
        limits:
          cpu: 100m
          memory: 512Mi

    persistence:
      storageClass: postgresql
      size: 4Gi

    metrics:
      enabled: true
      resources:
        requests:
          cpu: 5m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 128Mi