---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus
data:
  values.yaml: |
    server:
      priorityClassName: system-node-critical
      podDisruptionBudget:
        enabled: true
        maxUnavailable: 0

      persistentVolume:
        size: 4Gi
      retention: "7d"

      resources:
        requests:
          cpu: 10m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 256Mi
