---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
spec:
  chart:
    spec:
      chart: prometheus
      version: 25.8.1
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: sources
      interval: 12h0m0s
  interval: 1h0m0s
  valuesFrom:
    - kind: ConfigMap
      name: prometheus