---
apiVersion: v1
kind: ConfigMap
metadata:
  name: values
data:
  values.yaml: |
    server:
      priorityClassName: system-node-critical
      podDisruptionBudget:
        enabled: true
        maxUnavailable: 1
      replicaCount: 2
      statefulSet:
        enabled: true

      persistentVolume:
        storageClass: prometheus
        size: 4Gi
      retention: "7d"

      resources:
        requests:
          cpu: 100m
          memory: 512Mi
        limits:
          cpu: 1
          memory: 2048Mi
