---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: secrets-store-csi-driver
  namespace: secrets-store
spec:
  chart:
    spec:
      chart: secrets-store-csi-driver
      version: 1.4.0
      sourceRef:
        kind: HelmRepository
        name: secrets-store-csi-driver
        namespace: sources
      interval: 12h0m0s
  interval: 1h0m0s
  valuesFrom:
    - kind: ConfigMap
      name: secrets-store-csi-driver