---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: secrets-store-csi-driver
spec:
  chart:
    spec:
      chart: secrets-store-csi-driver
      sourceRef:
        kind: HelmRepository
        name: secrets-store-csi-driver
      interval: 12h0m0s
  interval: 1h0m0s
  values:
    syncSecret:
      enabled: true
    enableSecretRotation: true
    rotationPollInterval: 60s
    linux:
      priorityClassName: system-node-critical