---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kubelet-csr-approver
  namespace: flux-system
spec:
  interval: 1h0m0s
  retryInterval: 10s
  timeout: 30s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/infra/kubelet-csr-approver
  prune: true
  wait: true
  dependsOn:
    - name: sources