---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus
  namespace: flux-system
spec:
  interval: 1h0m0s
  retryInterval: 10s
  timeout: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/infra/prometheus
  prune: true
  wait: true
  dependsOn:
    - name: sources