---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra
  namespace: flux-system
spec:
  interval: 1h0m0s
  retryInterval: 10s
  timeout: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  wait: true
  dependsOn:
    - name: weave-gitops
    - name: cloudflare-tunnel