---
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    name: grafana
spec:
  deployment:
    spec:
      replicas: 2
      template:
        spec:
          volumes:
            - name: secrets
              csi:
                driver: secrets-store.csi.k8s.io
                readOnly: true
                volumeAttributes:
                  secretProviderClass: grafana
          containers:
            - name: grafana
              env:
                - name: GF_SECURITY_ADMIN_USER
                  valueFrom:
                    secretKeyRef:
                      key: admin-user
                      name: grafana
                - name: GF_SECURITY_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: admin-password
                      name: grafana
              volumeMounts:
                - name: secrets
                  mountPath: /etc/secrets
                  readOnly: true
  config:
    log:
      mode: console
    auth:
      disable_login_form: false
    database:
      type: postgres
      host: postgres-postgresql-ha-pgpool.postgres.svc.cluster.local:5432
      name: grafana
      user: grafana
      password: test