# roles/k8s_reset
---
galaxy_info:
  author: edgy_noodle
  description: Reset cluster
  role_name: k8s_reset

  min_ansible_version: "2.1"

  platforms:
    - name: Ubuntu
      versions: all
    - name: Debian
      versions: all

  galaxy_tags:
    - k8s

dependencies: []
