---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-subdir-external-provisioner
spec:
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: 4.0.18
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner
      interval: 12h0m0s
  interval: 1h0m0s
  values:
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 256Mi

    replicaCount: 2
    server: storage
    path: /export/volumes

    storageClass:
      defaultClass: true
      volumeBindingMode: WaitForFirstConsumer

    podDisruptionBudget:
      enabled: true
      maxUnavailable: 1