# roles/k8s_vault_add
---
- name: Register vault svc address
  set_fact:
    vault_address: "{{ vault_svc | json_query('resources[0].spec.clusterIP') }}:{{ vault_svc | json_query('resources[0].spec.ports[?name == `http`].port | [0]') }}"

- name: Get vault root token
  set_fact:
    root_token: "{{ lookup('file', '~/mono-repo/ansible/.vault-token') }}"

- name: Add secret
  community.hashi_vault.vault_write:
    path: "secret/data/{{ vault_secret_name }}"
    data:
      data:
        "{{ vault_secret_key }}: {{ vault_secret_value }}"
  when:
    - vault_secret_name is defined
    - vault_secret_key is defined
    - vault_secret_value is defined