---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
spec:
  chart:
    spec:
      chart: metrics-server
      version: 3.11.0
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: sources
      interval: 12h0m0s
  interval: 1h0m0s
  values:
    podDisruptionBudget:
      enabled: true
      maxUnavailable: 0