---
apiVersion: v1
kind: ConfigMap
metadata:
  name: values
data:
  values.yaml: |
    resources:
      requests:
        cpu: 5m
        memory: 48Mi
      limits:
        cpu: 100m
        memory: 128Mi

    podDisruptionBudget:
      enabled: true
      maxUnavailable: 0
