---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: consul
spec:
  chart:
    spec:
      chart: consul
      version: 1.3.0
      sourceRef:
        kind: HelmRepository
        name: hashicorp
      interval: 12h0m0s
  interval: 1h0m0s
  values:
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 256Mi

    global:
      datacenter: k8s
    client:
      enabled: true
    tls:
      enabled: true
    metrics:
      enabled: true
      enableAgentMetrics: true

    server:
      # https://developer.hashicorp.com/consul/docs/architecture/consensus#deployment-table
      replicas: 3
      disruptionBudget:
        maxUnavailable: 0