---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: consul
spec:
  chart:
    spec:
      chart: consul
      version: 1.3.0
      sourceRef:
        kind: HelmRepository
        name: hashicorp
      interval: 12h0m0s
  interval: 1h0m0s
  values:
    server:
      # https://developer.hashicorp.com/consul/docs/architecture/consensus#deployment-table
      replicas: 3
      disruptionBudget:
        maxUnavailable: 0
      priorityClassName: system-node-critical

      storage: 1Gi
      storageClass: consul

    client:
      enabled: true

    global:
      name: consul
      datacenter: k8s

      resources:
        requests:
          cpu: 100m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 256Mi

      tolerations: |
        - key: node-role.kubernetes.io/control-plane
          operator: Equal
          value: true
          effect: NoSchedule

      metrics:
        enabled: true
        enableAgentMetrics: true