---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: consul
provisioner: nfs-subdir-external-provisioner
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
parameters:
  server: storage
  path: /export/volumes
  readOnly: "false"