---
apiVersion: v1
kind: ConfigMap
metadata:
  name: values
data:
  values.yaml: |
    server:
      # https://developer.hashicorp.com/consul/docs/architecture/consensus#deployment-table
      replicas: 3
      disruptionBudget:
        maxUnavailable: 0
      priorityClassName: system-node-critical

      resources:
        requests:
          cpu: 10m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 256Mi
      storage: 1Gi
      storageClass: consul

    client:
      enabled: true
      resources:
        requests:
          cpu: 5m
          memory: 128Mi
        limits:
          cpu: 50m
          memory: 512Mi

    connectInject:
      enabled: false

    global:
      datacenter: k8s

      metrics:
        enabled: true
        enableAgentMetrics: true