apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cloudflare-tunnel.fullname" . }}
data:
  config.yaml: |
    tunnel: {{ .Values.cloudflare.tunnelName }}
    credentials-file: /etc/cloudflared/creds/credentials.json

    warp-routing:
      enabled: {{ .Values.cloudflare.warp }}
    metrics: 0.0.0.0:2000
    # Disabled in kubernetes as image state should be managed by deployment, not the pod.
    # Any updates would be lost on pod re-creation.
    no-autoupdates: true
    # https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/ingress
    ingress:
      {{- with .Values.cloudflare.ingress }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      - service: http_status:404