{{- if and (not .Values.cloudflare.local_vars.tunnelSecretName) (not .Values.cloudflare.remote_vars.tokenSecretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudflare-tunnel.fullname" . }}
  labels:
    {{- include "cloudflare-tunnel.labels" . | nindent 4 }}
stringData:
  {{- if not .Values.cloudflare.remote }}
  credentials.json: |-
    {
      "AccountTag": {{ .Values.cloudflare.local_vars.accountTag | quote }}
      "TunnelID": {{ .Values.cloudflare.local_vars.tunnelId | quote }}
      "TunnelSecret": {{ .Values.cloudflare.local_vars.tunnelSecret | quote }}
    }
  cert.pem: {{ .Values.cloudflare.local_vars.certSecretName }}
  {{- else }}
  tunnelToken: {{ .Values.cloudflare.remote_vars.token }}
  {{- end }}
{{- end }}