{{- if not .Values.cloudflare.tunnelSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudflare-tunnel.fullname" . }}
  labels:
    {{- include "cloudflare-tunnel.labels" . | nindent 4 }}
stringData:
  credentials.json: |-
    {
      "AccountTag": {{ .Values.cloudflare.accountTag | quote }}
      "TunnelID": {{ .Values.cloudflare.tunnelId | quote }}
      "TunnelSecret": {{ .Values.cloudflare.tunnelSecret | quote }}
    }
{{- end }}