---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-gitops
spec:
  chart:
    spec:
      chart: weave-gitops
      version: 4.0.35
      sourceRef:
        kind: HelmRepository
        name: weaveworks
        namespace: sources
      interval: 12h
  # https://github.com/weaveworks/weave-gitops/blob/main/charts/gitops-server/values.yaml
  interval: 1h0m0s
  valuesFrom:
    - kind: ConfigMap
      name: values