---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  interval: 60m
  chart:
    spec:
      chart: weave-gitops
      version: "4.0.35"
      sourceRef:
        kind: HelmRepository
        name: weaveworks
      interval: 12h
  # https://github.com/weaveworks/weave-gitops/blob/main/charts/gitops-server/values.yaml
  values:
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 256Mi
    securityContext:
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
    service:
      type: NodePort
    adminUser:
      create: true
      username: admin
      # Change password by generating a new hash with:
      # https://docs.gitops.weave.works/docs/configuration/securing-access-to-the-dashboard/#login-via-a-cluster-user-account
      passwordHash: "$2a$10$lWy9sSqaw6Vd0aOF7Wfsp.au6ikuve51p8P4xJ535eyaSYQQuAXyW"