---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: weave-gitops
spec:
  provider: vault
  secretObjects:
    - data:
        - key: clientID
          objectName: client-id
        - key: clientSecret
          objectName: client-secret
        - key: issuerURL
          objectName: issuer-url
        - key: redirectURL
          objectName: redirect-url
        - key: customScopes
          objectName: custom-scopes
      secretName: oidc-auth
      type: Opaque
    - data:
        - key: null
          objectName: null
      secretName: cluster-user-auth
      type: Opaque
  parameters:
    vaultAddress: http://vault.secrets-store.svc.cluster.local:8200
    roleName: default
    objects: |
      - objectName: client-id
        secretPath: secret/data/weave
        secretKey: client-id
      - objectName: client-secret
        secretPath: secret/data/weave
        secretKey: client-secret
      - objectName: issuer-url
        secretPath: secret/data/weave
        secretKey: issuer-url
      - objectName: redirect-url
        secretPath: secret/data/weave
        secretKey: redirect-url
      - objectName: custom-scopes
        secretPath: secret/data/weave
        secretKey: custom-scopes
      - objectName: null
        secretPath: secret/data/weave
        secretKey: null