---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-values
data:
  values.yaml: |
    replicas: 2
    headlessService: true

    podDisruptionBudget:
      minAvailable: 1

    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 256Mi

    persistence:
      size: 6Gi
