---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
spec:
  chart:
    spec:
      chart: grafana
      version: 7.0.13
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: sources
  interval: 1h0m0s
  valuesFrom:
    - kind: ConfigMap
      name: grafana