---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grafana
resources:
  - namespace.yaml
  - values.yaml
  - datasources.yaml
  - dashboardproviders.yaml
  - helmrelease.yaml