---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: grafana
spec:
  provider: vault
  secretObjects:
    - data:
        - key: admin-user
          objectName: grafana
        - key: admin-password
          objectName: grafana
      secretName: grafana
      type: Opaque
  parameters:
    vaultAddress: http://vault.secrets-store.svc.cluster.local:8200
    roleName: default
    objects: |
      - objectName: grafana
        secretPath: secret/grafana
        secretKey: admin-user
      - objectName: grafana
        secretPath: secret/grafana
        secretKey: admin-password
