---
apiVersion: v1
kind: ConfigMap
metadata:
  name: values
data:
  values.yaml: |
    podDisruptionBudget:
      minAvailable: 1

    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 256Mi

    persistence:
      size: 6Gi
      
    extraVolumeMounts:
      - name: secrets
        mountPath: /etc/secrets
        csi: true
        data:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: grafana

    admin:
      existingSecret: grafana
