---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubelet-csr-approver
spec:
  chart:
    spec:
      chart: kubelet-csr-approver
      version: 1.0.5
      sourceRef:
        kind: HelmRepository
        name: kubelet-csr-approver
        namespace: sources
      interval: 12h0m0s
  interval: 1h0m0s
  values:
    providerRegex: ^k8s-w[1-9]$
    providerIpPrefixes: 192.168.1.200/29