# roles/k8s_init
---
- name: Disable SWAP
  shell: swapoff -a

- name: Disable SWAP in fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- name: Load overlay module
  community.general.modprobe:
    name: overlay
    persistent: present

- name: Load br_netfilter module
  community.general.modprobe:
    name: br_netfilter
    persistent: present

- name: Copy 99-kubernetes-cri.conf CRI config
  copy:
    src: "{{ k8s_cri_conf }}"
    dest: /etc/sysctl.d/99-kubernetes-cri.conf
  register: sysctl_config

- name: Reload sysctl
  command: sysctl --system
  when: sysctl_config.changed

- name: Create keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory

- name: Download k8s keys
  get_url:
    url: "{{ k8s_key_url }} "
    dest: /etc/apt/keyrings/kubernetes-archive-keyring.asc

- name: Add k8s package repos
  deb822_repository:
    name: kubernetes
    types: deb
    suites: kubernetes-xenial
    components: main
    uris: https://apt.kubernetes.io/
    signed_by: /etc/apt/keyrings/kubernetes-archive-keyring.asc

- name: Install packages - containerd, k8s, pipx, jsonpatch, nfs-common
  package:
    name:
      - containerd
      - kubelet
      - kubeadm
      - kubectl
      - python3-kubernetes
      - python3-jsonpatch
      - pipx
      - nfs-common
    update_cache: true
    state: latest

- name: Create containerd directory
  file:
    path: /etc/containerd
    state: directory

- name: Generate containerd config
  shell: containerd config default | sudo tee /etc/containerd/config.toml

- name: Change SystemdCgroup to true in containerd config
  replace:
    path: /etc/containerd/config.toml
    regexp: 'SystemdCgroup = false'
    replace: 'SystemdCgroup = true'

- name: Disable automatic update for kubelet package
  dpkg_selections:
    name: kubelet
    selection: hold
- name: Disable automatic update for kubeadm package
  dpkg_selections:
    name: kubeadm
    selection: hold
- name: Disable automatic update for kubectl package
  dpkg_selections:
    name: kubectl
    selection: hold

- name: Reload configs
  systemd:
    daemon_reload: true
- name: Enable containerd service
  systemd:
    name: containerd
    enabled: true
    state: restarted
- name: Enable kubelet service
  systemd:
    name: kubelet
    enabled: true
    state: started

- name: Install k8s ansible collection dependency - openshift
  community.general.pipx:
    name: openshift
    install_deps: true
- name: Install k8s ansible collection dependency - pyyaml
  community.general.pipx:
    name: pyaml

- name: Add storage IP to hosts for PV config
  lineinfile:
    dest: /etc/hosts
    regexp: '{{ hostvars[item].ansible_default_ipv4.address }}.*{{ item }}$'
    line: "{{ hostvars[item].ansible_default_ipv4.address }} {{ item }}"
    state: present
  with_items: "{{ groups.storage }}"