---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secrets-store
  namespace: secrets-store
spec:
  provider: vault
  secretObjects:
    - data:
        - key: token
          objectName: cloudflare-tunnel
      secretName: cloudflare-tunnel
      type: Opaque
  parameters:
    vaultAddress: http://vault.default:8200
    roleName: secrets-store
    objects: |
      - objectName: cloudflare-tunnel
        secretPath: secret/cloudflare-tunnel
        secretKey: token