# roles/vms_init
---
- name: Install sudo
  package:
    name: sudo
    state: latest
    update_cache: yes

- name: Create ansible user
  user:
    name: ansible
    groups:
      - ansible
      - sudo
    shell: /bin/bash
  register: ansible

- name: Run sudo without password
  community.general.sudoers:
    name: ansible
    group: ansible
    nopassword: true
    commands: ALL

- name: Add SSH key for ansible user
  authorized_key:
    user: ansible
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAqWyHzwXS1oXk+Ir04eULYLBFT1nLIu7yoYGWlfq9Hy ansible"

- name: Update VMs
  include_role:
    name: vms_update