---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-subdir-external-provisioner
spec:
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: 4.0.18
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner
        namespace: sources
      interval: 12h0m0s
  interval: 1h0m0s
  valuesFrom:
    - kind: ConfigMap
      name: nfs-subdir-external-provisioner
