# roles/vms_init
---
- name: Install sudo
  package:
    name: sudo
    state: latest
    update_cache: true

- name: Create ansible user
  user:
    name: ansible
    groups: sudo
    shell: /bin/bash
    append: true
  register: ansible

- name: Run sudo without password
  community.general.sudoers:
    name: ansible
    group: ansible
    nopassword: true
    commands: ALL

- name: Get ansible SSK key
  local_action: command cat {{ ssh_key_path }}
  register: ssh_key

- name: Add SSH key for ansible user
  authorized_key:
    user: ansible
    key: "{{ ssh_key.stdout }}"

- name: Ensure correct hostname
  shell: sed -i "s/^127.0.1.1.*$/127.0.1.1\t$(hostname)/g" /etc/hosts