---
- name: Preliminary tasks and checks
  hosts: k8s
  become: true
  pre_tasks:
    - name: Fail fast if incompatible OS detected
      fail:
        msg: "OS should be Debian/Ubuntu, not {{ ansible_distribution }}"
      when: ansible_distribution not in ['Ubuntu', 'Debian']

- name: Provision all nodes
  hosts: k8s
  become: true
  roles:
    - name: k8s/k8s_all
      tags: k8s_init

- name: Provision CPN
  hosts: cpn
  roles:
    - name: k8s/k8s_cpn
      tags: k8s_init

- name: Provision worker nodes
  become: true
  hosts: workers
  roles:
    - name: k8s/k8s_workers
      tags: k8s_init

- name: Provision Flux
  hosts: cpn
  roles:
    - name: k8s/k8s_flux
      tags:
        - k8s_init
        - k8s_flux

- name: K8s vault init
  hosts: cpn
  roles:
    - name: k8s/k8s_vault
      tags: k8s_vault