---
- name: Bootstrap VMs
  hosts: all
  become: true
  become_method: su
  roles:
    - unix/vms_init

- name: Bootstrap NFS
  hosts: storage
  become: true
  become_method: su
  roles:
    - unix/nfs_init
