---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudflare-tunnel
  namespace: flux-system
spec:
  interval: 60m
  chart:
    spec:
      chart: cloudflared
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: cloudflare-tunnel
      interval: 12h
  values:
    replicaCount: 2
    tunnelId: b6c51afc-86b9-4550-9cee-dcc4be74be57
    existingSecret: cloudflared