---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cloudflare-tunnel
spec:
  chart:
    spec:
      chart: cloudflare-tunnel
      version: 1.0.1
      sourceRef:
        kind: HelmRepository
        name: edgy-noodle
        namespace: sources
      interval: 12h0m0s
  interval: 1h0m0s
  valuesFrom:
    - kind: ConfigMap
      name: values