---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudflare-tunnel
  namespace: flux-system
spec:
  interval: 60m
  chart:
    spec:
      chart: cloudflare-tunnel
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: cloudflare
      interval: 12h
  values:
    replicaCount: 2
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 256Mi

    cloudflare:
      secretName: cloudflared