---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudflare-tunnel
resources:
  - namespace.yaml
  - clusterrolebinding.yaml
  - secretproviderclass.yaml
  - deployment.yaml