# roles/k8s_vault
---
vault_aws_region: eu-west-2
secret: "{{ lookup('file', '~/mono-repo/ansible/.vault-password') }}"
vault_id: vault
policy_path: secrets-store
policy_content:
  path "secret/*" {
  capabilities = ["read", "list"]
  }
role_path: default
role_policies: secrets-store
role_sa_names:
  - default
  - weave-gitops
  - grafana-sa
role_sa_ns:
  - secrets-store
  - grafana
  - cloudflare-tunnel
  - postgres
  - weave-gitops