---
apiVersion: v1
kind: ConfigMap
metadata:
  name: initdbscripts
data:
  init.sh: |
    #!/bin/bash
    set -eou pipefail

    psql postgresql://postgres:$POSTGRES_PASSWORD@127.0.0.1:5432 <<EOF
      \x

      CREATE DATABASE infra;
      \c infra

      \set grafana_pwd `cat /etc/secrets/grafana-pass`
      CREATE ROLE grafana WITH LOGIN PASSWORD :'grafana_pwd';
      GRANT USAGE, CREATE ON SCHEMA public TO grafana;
      ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, UPDATE, INSERT, DELETE  ON TABLES TO grafana;
      ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE                           ON SEQUENCES TO grafana;
    EOF