---
apiVersion: v1
kind: ConfigMap
metadata:
  name: initdbscripts
data:
  init.sh: |
    #!/bin/bash
    set -eou pipefail

    psql postgresql://postgres:$POSTGRES_PASSWORD@127.0.0.1:5432 <<EOF
      \x
    
      CREATE DATABASE infra;
      \c infra
    
      CREATE SCHEMA grafana;
      \set grafana_pwd `cat /etc/secrets/grafana-pass`
      CREATE ROLE grafana WITH LOGIN PASSWORD :'grafana_pwd';
      ALTER DEFAULT PRIVILEGES IN SCHEMA grafana GRANT ALL PRIVILEGES ON TABLES TO grafana;
      ALTER DEFAULT PRIVILEGES IN SCHEMA grafana GRANT USAGE          ON SEQUENCES TO grafana;
    EOF