---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: postgres
resources:
  - namespace.yaml
  - secretproviderclass.yaml
  - storageclass.yaml
  - values.yaml
  - postgresql.yaml
  - pgpool.yaml
  - helmrelease.yaml