---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pgpool
data:
  pgpool.yaml: |
    pgpool:
      priorityClassName: system-node-critical
      pdb:
        create: true
        minAvailable: 1
      
      extraVolumes:
        - name: secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: postgresql
      extraVolumeMounts:
        - name: secrets
          mountPath: /etc/secrets
          readOnly: true
      existingSecret: postgresql
      
      resources:
        requests:
          cpu: 5m
          memory: 128Mi
        limits:
          cpu: 100m
          memory: 512Mi