---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql
data:
  postgresql.yaml: |
    postgresql:
      replicaCount: 3
      priorityClassName: system-node-critical
      pdb:
        create: true
        minAvailable: 2
      
      maxConnections: 40
      postgresConnectionLimit: 2
      dbUserConnectionLimit: 10
      
      extraVolumes:
        - name: secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: postgres
      extraVolumeMounts:
        - name: secrets
          mountPath: /etc/secrets
          readOnly: true
      existingSecret: postgres
      
      resources:
        requests:
          cpu: 5m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 128Mi