---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: postgres
spec:
  provider: vault
  secretObjects:
    - data:
        - key: password
          objectName: password
        - key: admin-password
          objectName: admin-password
        - key: repmgr-password
          objectName: repmgr-password
      secretName: postgres
      type: Opaque
    - data:
        - key: grafana-user
          objectName: grafana-user
        - key: grafana-pass
          objectName: grafana-pass
      secretName: grafana
      type: Opaque
  parameters:
    vaultAddress: http://vault.secrets-store.svc.cluster.local:8200
    roleName: default
    objects: |
      - objectName: password
        secretPath: secret/data/postgres
        secretKey: master-pass
      - objectName: repmgr-password
        secretPath: secret/data/postgres
        secretKey: master-pass
      - objectName: admin-password
        secretPath: secret/data/postgres
        secretKey: master-pass
      - objectName: grafana-user
        secretPath: secret/data/postgres
        secretKey: grafana-user
      - objectName: grafana-pass
        secretPath: secret/data/postgres
        secretKey: grafana-pass