---
apiVersion: v1
kind: ConfigMap
metadata:
  name: values
data:
  values.yaml: |
    persistence:
      storageClass: postgres
      size: 4Gi

    metrics:
      enabled: true
      resources:
        requests:
          cpu: 5m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 128Mi