---
- hosts: all
  become: true
  tasks:

  - name: Update repo index
    apt:
      update_cache: yes

  - name: Install packages
    apt:
      name:
        - bash-completion
        - bridge-utils
        - net-tools
        - cloud-utils