---
- hosts: all
  become: true
  tasks:

  - name: Update repo index
    apt:
      update_cache: yes
    when: ansible_distribution == "Debian"

  - name: Install packages
    apt:
      name:
        - bash-completion
        - bridge-utils
        - net-tools
        - cloud-utils
      state: latest
    when: ansible_distribution == "Debian"