# roles/k8s_vault
---
- name: Define AWS KMS secret
  kubernetes.core.k8s:
    state: present
    api_version: v1
    kind: Secret
    name: kms-creds
    namespace: secrets-store
    resource_definition:
      data:
        AWS_ACCESS_KEY_ID: "{{ vault_aws_access_key_id | b64encode }}"
        AWS_SECRET_ACCESS_KEY: "{{ vault_aws_secret_access_key | b64encode }}"
        AWS_REGION: "{{ vault_aws_region | b64encode }}"
        AWS_KMS_KEY_ID: "{{ vault_aws_kms_key_id | b64encode }}"
  when:
    - vault_aws_access_key_id is defined
    - vault_aws_secret_access_key is defined
    - vault_aws_region is defined
    - vault_aws_kms_key_id is defined

- name: Check if vault is running
  kubernetes.core.k8s_info:
    kind: Pod
    name: vault-0
    namespace: secrets-store
    wait: true
    wait_condition:
      status: True
      type: Initialized
    wait_timeout: 180
  register: vault_running

- name: Verify vault connectivity
  kubernetes.core.k8s_exec:
    pod: vault-0
    namespace: secrets-store
    command: vault status
  register: vault_status
  ignore_errors: true
  failed_when: false
  no_log: True

- name: Initialize vault
  kubernetes.core.k8s_exec:
    pod: vault-0
    namespace: secrets-store
    command: vault operator init
  register: vault_init
  when:
    - vault_running.resources[0] is defined
    - (vault_running | json_query("resources[0].status.conditions[?type=='Ready'].status"))[0] == "False"
    - vault_status.stdout_lines[3] is defined
    - vault_status.stdout_lines[3] is search("false")

- name: Save recovery keys
  local_action:
    module: copy
    dest: ~/mono-repo/ansible/.vault-keys
    content: |
      "{{ recovery_key_1 }}"
      "{{ recovery_key_2 }}"
      "{{ recovery_key_3 }}"
      "{{ recovery_key_4 }}"
      "{{ recovery_key_5 }}"
  when: vault_init.changed
  vars:
    recovery_key_1: "{{ (vault_init.stdout_lines[0] | split(':'))[1] | vault(secret, vault_id) }}"
    recovery_key_2: "{{ (vault_init.stdout_lines[1] | split(':'))[1] | vault(secret, vault_id) }}"
    recovery_key_3: "{{ (vault_init.stdout_lines[2] | split(':'))[1] | vault(secret, vault_id) }}"
    recovery_key_4: "{{ (vault_init.stdout_lines[3] | split(':'))[1] | vault(secret, vault_id) }}"
    recovery_key_5: "{{ (vault_init.stdout_lines[4] | split(':'))[1] | vault(secret, vault_id) }}"

- name: Save root token
  local_action:
    module: copy
    dest: ~/mono-repo/ansible/.vault-token
    content: |
      {{ root_token }}
  when: vault_init.changed
  vars:
    root_token: "{{ (vault_init.stdout_lines[6] | split(':'))[1] | trim | vault(secret, vault_id) }}"

- name: Vault login
  kubernetes.core.k8s_exec:
    pod: vault-0
    namespace: secrets-store
    command: vault login {{ root_token }}
  vars:
    root_token: "{{ lookup('file', '~/mono-repo/ansible/.vault-token') }}"

- name: Check for k8s auth
  kubernetes.core.k8s_exec:
    pod: vault-0
    namespace: secrets-store
    command: vault auth list -format="json"
  register: vault_auth

- name: Enable k8s auth
  kubernetes.core.k8s_exec:
    pod: vault-0
    namespace: secrets-store
    command: vault auth enable kubernetes
  when: not vault_auth.stdout is search("kubernetes")

- name: Get k8s API data
  kubernetes.core.k8s_exec:
    pod: vault-0
    namespace: secrets-store
    command: >
      sh -ec 'env | grep -E "KUBERNETES_PORT_443_TCP_(PORT|ADDR)" | sort'
  register: k8s_api

- name: Configure k8s auth
  kubernetes.core.k8s_exec:
    pod: vault-0
    namespace: secrets-store
    command: vault write auth/kubernetes/config kubernetes_host="https://{{addr}}:{{port}}"
  vars:
    addr: "{{ (k8s_api.stdout_lines[0] | split('='))[1] }}"
    port: "{{ (k8s_api.stdout_lines[1] | split('='))[1] }}"

- name: Check for kv engine
  kubernetes.core.k8s_exec:
    pod: vault-0
    namespace: secrets-store
    command: vault secrets list -format="json"
  register: vault_kv

- name: Enable kv engine
  kubernetes.core.k8s_exec:
    pod: vault-0
    namespace: secrets-store
    command: vault secrets enable -path=secret kv
  when: not vault_kv.stdout is search("secret")

- name: Copy policy file
  copy:
    src: "{{ vault_policy }}"
    dest: ~/secrets-store.hcl

- name: Create secrets-store policy
  kubernetes.core.k8s_exec:
    pod: vault-0
    namespace: secrets-store
    command: vault policy write secrets-store ~/secrets-store.hcl

- name: Create default role
  kubernetes.core.k8s_exec:
    pod: vault-0
    namespace: secrets-store
    command: >
      vault write auth/kubernetes/role/default bound_service_account_names=default \
      bound_service_account_namespaces=grafana,cloudflare-tunnel,postgresql policies=secrets-store ttl=20m