---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana-operator
spec:
  chart:
    spec:
      chart: grafana-operator
      version: 3.5.11
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: sources
  interval: 1h0m0s
  valuesFrom:
    - kind: ConfigMap
      name: values