---
apiVersion: v1
kind: ConfigMap
metadata:
  name: values
data:
  values.yaml: |
    operator:
      namespaceScope: true
      watchNamespace: grafana
      priorityClassName: system-node-critical

    grafana:
      enabled: false
