---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault
  namespace: secrets-store
data:
  values.yaml: |
    csi:
      enabled: true
      resources:
        requests:
          cpu: 5m
          memory: 64Mi
        limits:
          cpu: 50m
          memory: 256Mi
    injector:
      enabled: false

    server:
      priorityClassName: system-node-critical
      ha:
        enabled: true
        replicas: 3
        disruptionBudget:
          maxUnavailable: 1

        config: |
          listener "tcp" {
            tls_disable = 1
            address = "[::]:8200"
            cluster_address = "[::]:8201"
          }
          storage "consul" {
            path        = "vault"
            address     = "HOST_IP:8500"
          }
          seal "awskms" {
            region      = "AWS_REGION"
            kms_key_id  = "AWS_KMS_KEY_ID"
          }
          service_registration "kubernetes" {}

      resources:
        requests:
          cpu: 10m
          memory: 128Mi
        limits:
          cpu: 100m
          memory: 512Mi

      service:
        type: NodePort

      postStart:
        - /bin/sh
        - -c
        - sed -i -e "s/AWS_REGION/$AWS_REGION/g" -e "s/AWS_KMS_KEY_ID/$AWS_KMS_KEY_ID/g" /tmp/storageconfig.hcl

      extraSecretEnvironmentVars:
        - envName: AWS_ACCESS_KEY_ID
          secretName: kms-creds
          secretKey: AWS_ACCESS_KEY_ID
        - envName: AWS_SECRET_ACCESS_KEY
          secretName: kms-creds
          secretKey: AWS_SECRET_ACCESS_KEY
        - envName: AWS_REGION
          secretName: kms-creds
          secretKey: AWS_REGION
        - envName: AWS_KMS_KEY_ID
          secretName: kms-creds
          secretKey: AWS_KMS_KEY_ID
