---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault
  namespace: secrets-store
data:
  values.yaml: |
    csi:
      enabled: true
    injector:
      enabled: false

    server:
      priorityClassName: system-node-critical
      ha:
        enabled: true
        replicas: 3
        disruptionBudget:
          maxUnavailable: 1

        config: |
          listener "tcp" {
            tls_disable = 1
            address = "[::]:8200"
            cluster_address = "[::]:8201"
          }
          storage "consul" {
            path        = "vault"
            address     = "HOST_IP:8500"
          }
          seal "awskms" {
            region      = "$AWS_REGION"
            kms_key_id  = "$AWS_KMS_KEY_ID"
          }
          service_registration "kubernetes" {}

      extraSecretEnvironmentVars:
        - envName: AWS_ACCESS_KEY_ID
          secretName: kms-creds
          secretKey: AWS_ACCESS_KEY_ID
        - envName: AWS_SECRET_ACCESS_KEY
          secretName: kms-creds
          secretKey: AWS_SECRET_ACCESS_KEY
        - envName: AWS_REGION
          secretName: kms-creds
          secretKey: AWS_REGION
        - envName: AWS_KMS_KEY_ID
          secretName: kms-creds
          secretKey: AWS_KMS_KEY_ID
