---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: secrets-store
spec:
  chart:
    spec:
      chart: vault
      version: 0.27.0
      sourceRef:
        kind: HelmRepository
        name: hashicorp
      interval: 12h0m0s
  interval: 1h0m0s
  values:
    csi:
      enabled: true
    injector:
      enabled: false

    server:
      ha:
        enabled: true
        replicas: 2
        config: |
          listener "tcp" {
            tls_disable = 1
            address = "[::]:8200"
            cluster_address = "[::]:8201"
          }
          storage "consul" {
            path        = "vault"
            address     = "HOST_IP:8500"
          }
          seal "awskms" {
            region      = "eu-west-2"
            kms_key_id  = "73084880-8ab2-48e3-a3ab-b337afdc144c"
          }
          service_registration "kubernetes" {}

      extraSecretEnvironmentVars:
        - envName: AWS_ACCESS_KEY_ID
          secretName: kms-creds
          secretKey: AWS_ACCESS_KEY_ID
        - envName: AWS_SECRET_ACCESS_KEY
          secretName: kms-creds
          secretKey: AWS_SECRET_ACCESS_KEY