---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: secrets-store
spec:
  chart:
    spec:
      chart: vault
      version: 0.27.0
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: sources
      interval: 12h0m0s
  interval: 1h0m0s
  valuesFrom:
    - kind: ConfigMap
      name: vault