---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault-csi-provider
spec:
  chart:
    spec:
      chart: vault
      version: 1.4.1
      sourceRef:
        kind: HelmRepository
        name: hashicorp
      interval: 12h0m0s
  interval: 1h0m0s
  values:
    csi:
      enabled: true
    injector:
      enabled: false
    server:
      ha:
        enabled: true