name: 'fluxe2e_gha'
on:
  pull_request:
    branches: [ main ]
    paths:
      - 'flux/**'
  push:
    branches: [ main ]
    paths:
      - 'flux/**'
  workflow_dispatch:

jobs:
  flux-e2e:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Setup Flux'
        uses: fluxcd/flux2/action@main
      - name: 'Setup Kubernetes'
        uses: helm/kind-action@v1.7.0
        with:
          cluster_name: flux
      - name: 'Install Flux in Kind'
        run: flux install
      - name: 'Setup cluster reconciliation'
        run: |
          flux create source git flux-system \
          --url=${{ github.event.repository.html_url }} \
          --branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}} \
          --username=${GITHUB_ACTOR} \
          --password=${{ secrets.GITHUB_TOKEN }} \
          --ignore-paths="flux/clusters/**/flux-system/"
          flux create kustomization flux-system \
          --source=flux-system \
          --path=./flux/clusters/dev
      - name: 'Verify cluster reconciliation'
        run: |
          kubectl wait -n flux-system kustomization --all --for=condition=ready --timeout=3m
      - name: 'Verify helm reconciliation'
        run: |
          kubectl wait -A helmrelease --all --for=condition=ready --timeout=5m
      - name: 'Debug failure'
        if: failure()
        run: |
          kubectl -n flux-system get all
          kubectl -n flux-system logs deploy/source-controller
          kubectl -n flux-system logs deploy/kustomize-controller
          kubectl -n flux-system logs deploy/helm-controller
          flux get all --all-namespaces