name: 'shellcheck_gha'
on:
  pull_request:
    branches: [ main ]
    paths:
      - "**.sh"
  push:
    branches: [ main ]
    paths:
      - "**.sh"

jobs:
  shellcheck:
    name: 'shellcheck'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Check'
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: './resources/scripts'
        env:
          SHELLCHECK_OPTS: -e SC1090 -e SC2013