name: 'shellcheck_gha'
on:
  - pull_request
jobs:
  shellcheck:
    name: 'shellcheck'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Check'
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: './resources/scripts'