name: 'structure_gha'
on:
  pull_request:
    branches: [ main ]

jobs:
  update-readme:
    name: 'structure'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Install tree'
        run: sudo apt-get install tree
      - name: 'Generate structure'
        run: |
          {
            echo "STRUCT<<EOF"
            echo "$(tree -d --noreport --charset=unicode)"
            echo EOF
          } >> "$GITHUB_ENV"
      - name: 'Remove previous struct block'
        run: sed -ie '/```struct/,/```/c ```struct' README.md
      - name: 'Replace the dreaded pipes'
        run: sed 's\|\ \g'<<<"${{env.STRUCT}}" > temp
      - name: 'Add new structure'
        run: sed -ie "/```struct/r temp" README.md
      - name: 'Finish struct block'
        run: sed -ie '/## Usage/i ```\n' README.md
      - name: Commit and push changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: structure_gha
          author_email: mono-repo@edgy-noodle.com
          message: "docs: update README with repo structure"
          add: "README.md"