name: 'structure_gha'
on:
  push:
    branches: [ main ]

jobs:
  update-readme:
    name: 'structure'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Install tree'
        run: sudo apt-get install tree
      - name: 'Generate structure'
        run: tree -d -L 4 --noreport --charset=unicode > structure.txt
      - name: 'Replace structure'
        run: python resources/gha/structure.py
        env:
          STRUCTURE: structure.txt
      - name: 'Create PR'
        uses: peter-evans/create-pull-request@v5
        with:
          add-paths: 'README.md'
          commit-message: 'docs: update README with repo structure'
          author: 'structure_gha <mono-repo@edgy-noodle.com>'
          branch: 'structure_gha'
          labels: 'automerge'
      - name: 'Merge'
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          MERGE_METHOD: 'squash'