name: 'structure_gha'
on:
  pull_request:
    branches: [ main ]

jobs:
  update-readme:
    name: 'structure'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Install tree'
        run: sudo apt-get install tree
      - name: 'Generate structure'
        run: |
          {
            echo "STRUCT<<EOF"
            echo "$(tree -d --noreport --charset=unicode)"
            echo EOF
          } >> "$GITHUB_ENV"
      - name: 'Replace/add in README'
        run: |
          if ! grep -q '^```struct$' README.md; then
            echo "```struct\n${{env.STRUCT}}\n```" | sed -i '/^## Structure$/r /dev/stdin' README.md
          else
            echo "```struct\n${{env.STRUCT}}\n```" | sed -i '/^```struct$/,/```/r /dev/stdin' README.md
          fi
      - name: Commit and push changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: structure_gha
          author_email: mono-repo@edgy-noodle.com
          message: "docs: update README with repo structure"
          add: "README.md"