name: 'structure_gha'
on:
  pull_request:
    branches: [ main ]

jobs:
  update-readme:
    name: 'structure'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Install tree'
        run: sudo apt-get install tree
      - name: 'Generate structure'
        run: |
          {
            echo 'STRUCT<<EOF'
            $(tree -d --noreport)
            echo EOF
          } >> "$GITHUB_ENV"
      - name: 'Prepend to README'
        run: |
            echo "${{env.STRUCT}}" | sed '/^## Structure$/r /dev/stdin' README.md > temp && mv temp README.md
      - name: Commit and push changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: structure_gha
          author_email: mono-repo@edgy-noodle.com
          message: "docs: update README with repo structure"
          add: "README.md"