name: 'structure_gha'
on:
  push:
    branches: [ main ]

jobs:
  update-readme:
    name: 'structure'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Install tree'
        run: sudo apt-get install tree
      - name: 'Generate structure'
        run: tree -d -L 4 --noreport --charset=unicode > structure.txt
      - name: 'Replace structure'
        run: python resources/gha/structure.py
        env:
          STRUCTURE: structure.txt
      - name: Commit and push changes
        uses: EndBug/add-and-commit@v7
        with:
          fetch: true
          author_name: structure_gha
          author_email: mono-repo@edgy-noodle.com
          message: 'docs: update README with repo structure'
          add: README.md