name: 'structure_gha'
on:
  pull_request:
    branches: [ main ]

jobs:
  update-readme:
    name: 'structure'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Install tree'
        run: sudo apt-get install tree
      - name: 'Generate structure'
        run: tree -d --noreport --charset=ascii > structure.txt
      - name: Read repo structure
        id: structure
        uses: juliangruber/read-file-action@v1
        with:
          path: ./structure.txt
      - name: 'Remove previous struct block'
        run: sed -ie '/```struct/,/```/c ```struct' README.md
      - name: 'Add new structure'
        run: echo "${{steps.structure.outputs.content}}" | sed -ie "/```struct/r /dev/stdout" README.md
      - name: 'Finish struct block'
        run: sed -ie '/## Usage/i ```\n' README.md
      - name: Commit and push changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: structure_gha
          author_email: mono-repo@edgy-noodle.com
          message: "docs: update README with repo structure"
          add: "README.md"