name: 'yamllint_gha'
on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '.github/**'
    paths:
      - '**.yml'
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/**'
    paths:
      - '**.yml'

jobs:
  yamllint:
    name: 'yamllint'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Lint'
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_file_or_dir: resources/gha/.yamllint
          yamllint_strict: false
          yamllint_comment: true
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}