name: 'yamllint_gha'
on:
  - pull_request
jobs:
  yamllint:
    name: 'yamllint'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Lint'
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_file_or_dir: .yamllint
          yamllint_strict: false
          yamllint_comment: true
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}